### ISSUE TITLE
Can't paste into static password configuration

### ISSUE THREAD

**Issue by devicenull** [Yubico/yubikey-manager#149]
I was trying to sync my static password while moving from an older yubikey to a new one, and it's very annoying that I cannot paste a password in the 'Configure static password' dialog.

I also can't just use my old Yubikey to type it in, because Yubikey Manager won't work with multiple connected keys.

It sucks having to retype a 48 character password.

**Comment by dagheyman** [comment]
I'm assuming this is in the GUI.

It is possible to paste in that field, but you may need to check `[ ] Allow any character` if your password have other characters than `cbdefghijklnrtuv`. Even so, YubiKey Manager only allows up to 38 characters because it only supports Scan Code mode.

Thanks for the feedback though, will look into if the UX here can be improved.
