### ISSUE TITLE
Ykman doesn't see the key, when piv tool works fine.

### ISSUE THREAD

**Issue by leiocalyx** [Yubico/yubikey-manager#234]
- YubiKey Manager (ykman) version: 
YubiKey Manager (ykman) version: 2.1.0
Libraries:
    libykpers 1.19.3
    libusb 1.0.22
- How was it installed?:
Bundled with GUI. 
- Operating system and version:
Windows 10 10.0.17763 running on Hyper-v with enhanced session
- YubiKey model and version:
Yubikey 4 (4.3.7)
- Bug description summary:

ykman doesn't see the yubikey for some reason (gui doesn't recognize it as well)

Steps to reproduce
---
insert yubikey
run .\ykman.exe info

Expected result
---
Device type: YubiKey 4
Serial number: 7837506
Firmware version: 4.3.7
Enabled USB interfaces: OTP+FIDO+CCID

Applications
OTP             Enabled
FIDO U2F        Enabled
OpenPGP         Enabled
PIV             Enabled
OATH            Enabled
FIDO2           Not available

Actual results and logs
---
.\ykman.exe info
Usage: ykman.exe [OPTIONS] COMMAND [ARGS]...
Try "ykman.exe -h" for help.

Error: No YubiKey detected!

Other info
---
Yubico piv tool works fine, though:

PS C:\yubi\bin> .\yubico-piv-tool.exe -V
yubico-piv-tool 1.7.0
PS C:\yubi\bin> .\yubico-piv-tool.exe -alist
Yubico Yubikey 4 OTP+U2F+CCID 0

**Comment by dagheyman** [comment]
Hi, thanks for the report.

So this is in a VM? The reason could be that USB pass-through is not working. ykman uses USB descriptors to identify the device, while yubico-piv-tool talks directly to the CCID reader. You could try 
` $ ykman --reader yubico info` to use the reader directly.

**Comment by leiocalyx** [comment]
Yes, it works with the command you provided. 

Any reason not to have it default to that? There is `-d <serial number>` for those who (I'm guessing) have several yubikeys connected, but is there anything else to be used with `--reader` other than a `yubikey`?

**Comment by dagheyman** [comment]
> is there anything else to be used with --reader other than a yubikey

It can be used to specify a non-default smart-card reader as well, for example an NFC reader.

If we don't find any YubiKeys when looking at USB descripors, maybe we could try too look for default CCID reader names even without the flag specified (to support the VM / RDP use case). I'll have to think about it a bit.

**Comment by dragon788** [comment]
Improved smart card forwarding support would be awesome.

I've had a similar but separate issue where I think I know the problem, but not a good fix.

I use Karabiner-Elements and because it grabs all HID input devices, sometimes it seems to interrupt the Yubikey instantiating the GPG/PIV/OATH functionality and I can do a `gpg --card-status` but `ykman oath` fails, or I can `ykman oath` but then `gpg --card-status` fails.

The "quick" fix is to plug and unplug the card a few times to signal Karabiner-Elements to ignore the device, but that also isn't a great fix because as I learned today, some people are actually using Karabiner-Elements to remap the Yubikey's HID to Qwerty if their system keyboard is set to Colemak or Dvorak or something where it might alter how the keycodes are interpreted coming from the Yubikey.

**Comment by dainnilsson** [comment]
This handling has been improved for ykman 4.0, and should now work in the same cases when yubico-piv-tool works. Please open a new issue if this persists!
