### ISSUE TITLE
Can't program YubiKey as CHAL_YUBICO with ykman

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Yubico/yubikey-manager#29]
It looks like 'ykman slot chalresp 2' will only ever program the YubiKey as HMAC instead. We'd like to use the CHAL_YUBICO mode instead.

**Comment by dainnilsson** [comment]
Hi,
This tool probably won't support that feature as it is very rarely used. `ykpersonalize` will continue to support it, and I would refer you to that tool if you absolutely require CHAL_YUBICO.

I'm curious to why you're using that mode rather than the much more common HMAC-SHA1 mode though, would you be able to share your use-case?

**Comment by dagheyman** [comment]
Closing for now.
