### ISSUE TITLE
Feature request: TOTP time-to-live report

### ISSUE THREAD

**Issue by abridgett** [Yubico/yubikey-manager#310]
- YubiKey Manager (ykman) version: 3.1.0
- How was it installed?: apt repo
- Operating system and version: ubuntu 20.04
- YubiKey model and version: 5c
- Bug description summary: (feature request): ability to discover TOTP TTL

I'm writing a tool to integrate with AWS CLI and one issue is going to be when people re-use the same TOTP (i.e. try and use the same one before the next one comes along).

For this reason it'd be really useful to be able to find out how long is left on the generated TOTP code (in fact, even better if it's possible to do this _without_ the touch requirement as it will lead to less user-interaction for my use case).

`ykman oath list -p` just lists the period of the TOTP codes (i.e. "30" for us) - it doesn't say how long is left on the _current_ code.

**Comment by tl-adrian-bridgett** [comment]
Just looking at this (yay for source code!) and I see that in ykman/cli/oath.py:347 the validity is always time.tim()%30.  Which, assuming it's correct is easy to figure out (since UTC, ignore timestamps).  I hadn't realised they were all synchronised like this - I should read the spec :-)

As such I think this feature isn't really needed (thought might be handy), please feel _very_ free to close.

**Comment by dagheyman** [comment]
Thanks for the suggestion, it's possible but I don't think it is as useful in a CLI setting as in a running authenticator app. Note that most services typically allow the last and upcoming TOTP code as well, to avoid this issue (not sure about how AWS does it).
