### ISSUE TITLE
Support multiple yubikeys

### ISSUE THREAD

**Issue by jonasfj** [Yubico/yubikey-manager#32]
Currently it just writes:
`Error: Multiple YubiKeys detected. Only a single YubiKey at a time is supported.`

multi-key support is important as we have different security levels..

And it's really hard in my nails :) to drag an yubikey nano out of it's slot because I've temporary inserted a more trusted yubikey in another slot.

**Comment by emlun** [comment]
Unfortunately this is much more complicated than it may seem.

The first half of the problem is technical limitations. Some of the interfaces to the YubiKey hardware can indeed differentiate between devices, but the issue is that there's no real way to connect this information between interfaces. For example, we may be able to identify separate YubiKeys in libusb, but there's no guarantee that we can get the same identification in libccid when we need to actually do something with the key.

Even if we do find a way to solve the technical issues, the second half is making it all comprehensible to the user. Supporting multiple YubiKeys for some but not all features would be confusing. There's also not really much point in supporting multiple YubiKeys if in the end the utility has to ask "Do you want to program YubiKey A or YubiKey B?" - especially if those names may change when you disconnect and reconnect them, or connect a third key, or restart the CCID daemon, or when the OS randomly refreshes its peripherals directory, etc.

We might find a way to do it eventually, but honestly we currently don't have any good ideas on how to do it without inviting hordes of bugs. Single key support only is the least confusing solution we have at this time.

**Comment by Sp8c3** [comment]
I thing you search for something like [this](https://github.com/Sp8c3/YubiTool)
