### ISSUE TITLE
ykman list -s depends on USB descriptors and does not use API

### ISSUE THREAD

**Issue by dragon788** [Yubico/yubikey-manager#364]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: Homebrew
- Operating system and version: macOS 10.15.7
- YubiKey model and version: Yubikey 4 nano USB-C
- Bug description summary: ykman list -s with a yk5 and yk4 inserted only showed a serial number for the yk5 when the `usb-descriptor` setting was disabled (a default?) on the yk4.

I have multiple yubikeys to handle the number of TOTP/OATH accounts I have set up, and I was hoping to be able to access codes from either key, which appears to be possible according to the `ykman oath show` suggesting I pass `--device deviceSerial` but with the default setting not showing the device serial for the yk4 I had to temporarily resort to unplugging the other Yubikey to get my code.

I went and found the setting in the Yubikey Personalization GUI to show the serial via USB descriptor and enabled it which fixed the display of `ykman list -s` but I'm curious about the security implications of showing the serial number as part of the descriptor, whether .

I also tried the CLI personalization tool but the command syntax was very strange, and passing -N0 or -N1 _might_ switch to the other key, but passing `-N0` or `-N1` and running the command multiple times using the name number resulted in the key changing 1/3-1/4 of the time.

Steps to reproduce
---

Plugged in two Yubikeys and run `ykman oath list`.

Expected result
---

The ability to specify which Yubikey to query for a given TOTP/OATH code by serial number or "device number" even if serial numbers aren't visible/enabled for the devices via `ykman list -s`. 

Actual results and logs
---

The `ykman oath list` command suggests passing `--device deviceSerial` but running `ykman list -s` only showed the serial for one device, and the device name for the other.

The help text should be clarified what to do if the `ykman list` and `ykman list -s` don't return serials for every device, and perhaps rather than typing a whole serial, an index based selection alternative would be helpful, ie `[0] Yubikey 5 Serial: 123456 [1] Yubikey 4 Serial: Not Detected` and then a user could pass the index digit(s) to the `--device [index | serial]`.

If they have more than 0-9 Yubikeys plugged in, they have bigger challenges, but I think it would be safe to handle 1 to 3 digits as valid entries for the index and ~7 digits denotes a serial number, and I'd think the user supplied index could easily be compared against the length of the detected Yubikey count, in case they had a 100+ devices plugged in for bulk provisioning via USB2.0 hubs like the Cambrionix SyncPad54 or Orico 30 port or similar.

**Comment by dainnilsson** [comment]
There are two relevant configuration flags for the YubiKey: `SERIAL_USB_VISIBLE` and `SERIAL_API_VISIBLE`. The first one of these does what you describe: Puts the serial number in the USB descriptor.  `ykman list` as well as `ykman --device <serial>` actually DON'T use this, and will never look at the serial in the device descriptor. Instead the second one (`SERIAL_API_VISIBLE`) is used, which provides access to read the serial number from the YubiKey programmatically. This is by default enabled, and required to be so for most ykman commands when more than one key is present.

This doesn't match with your description of events, so I have to assume something else was causing the issues you were seeing. I'd suggest upgrading to ykman 4.0 and trying again. If you see behavior that isn't consistent with using the serial from `SERIAL_API_VISIBLE` then please feel free to open a new issue.

Handling this via some other identifier, such as an index, is very tricky to do as you'd want the indexing to remain stable between invocations of the tool. You'd have to consider cross-platform compatibility, the fact that some of the commands cause the YubiKey to re-enumerate (effectively unplug, replug), and that a single YubiKey often shows up as multiple devices due to the different connection types available. I'm not sure how we would go about solving this.
