### ISSUE TITLE
Missing feature: ykman piv export-publickey [SLOT] [KEYFILE]

### ISSUE THREAD

**Issue by Torxed** [Yubico/yubikey-manager#375]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: pacman (arch linux), also tried git source compile
- Operating system and version: Arch Linux latest
- YubiKey model and version: YubiKey 4
- Bug description summary:

When using a Yubikey as a CA for test purposes.
Signing certificates for SSH as an example after keys on the Yubikey is generated is extremely tedious since `ykman` is missing a `PIV` feature to extract the public key after the key pairs are generated.

Steps to reproduce
---

```
ykman piv generate-key [OPTIONS] 9a test_ca.pubkey
ykman piv generate-certificate [OPTIONS] 9a test_ca.pubkey
```

Now, if you want to do something like:
```
ssh-keygen -I YUBIKEY_CN -s test_ca.pub -D /usr/lib/pkcs11/opensc-pkcs11.so -n CN -V +1d -z 1 user.pub
```

That would require that you saved `test_ca.pubkey` somewhere *(and did some conversions)*.
Which seams odd, because it would be more appropriate to export the public part of the key when needed, from the hardware, rather than saving it in software some where risking version changes and mixups.

You could extract it with `pkcs15-tool --read-ssh-key 01 --reader 1` and you'll get it. The problem with that method is that there's no way to verify which `--reader` the CA is inserted to at the time of signing. At least not in any meaningful way *(you could insert the CA first, find which reader that got assigned to (guessing 0 every time) and then continue the signing process)*. The only way is to iterate over every reader with `pkcs15-tool` and export the certificate, and do the same with `ykman` and match which reader-id belongs to which yubikey serial/device. Which requires a lot of extracting and calling devices multiple times.

But programatically, it's illogical that there's no way to export it from the tool where you create the key pairs and have the trust/verification that you're working with the correct data. Which is lost when you need to switch tools back and fourth.

**Comment by dainnilsson** [comment]
The PIV specification offers no mechanism for extracting a public key from a key stored on a card - it's ONLY returned from the card upon on-card generation. Thus, unless you save the public key at that time, it will be lost. For most PIV use-cases, that public key will be used in a X509 certificate, which will then be stored in the corresponding slot on the card. Since the certificate is readable, this also makes the public key readable, albeit indirectly. I would assume this is what pksc15-tool might be doing.

YubiKeys offer additional options in the vendor specific attestation command - This command will generate an attestation-key signed X509 certificate for any private key (the certificate will then contain the public key) which was generated on-chip in the YubiKey (not for imported keys). This can be used to extract a public key from the YubiKey. More info on this is available here: https://developers.yubico.com/PIV/Introduction/PIV_attestation.html

Both of these will yield X509 certificates containing the public key, so there will still be some extraction/conversion required if you want a different format.

**Comment by Torxed** [comment]
From a user standpoint, ignoring certain specifications, it would be extremely handy to have a parameter to `ykman` that does exactly this. It's apparent that this is technically possible as long as there's a certificate stored and that it's simply a specification limitation *(perhaps the wrong choice of word but you get the idea)*.

I'm using the tool to administrate my yubikey, not to follow specifications.
There for I would like to suggest that this flag/feature is implemented but not necessarily under the PIV hierarchy.
If this goes against some principles then this ticket can be closed.

**Comment by dainnilsson** [comment]
We'll consider adding something like this to the tool.

**Comment by dainnilsson** [comment]
This has been added to ykman 4.0 (currently in alpha).
