### ISSUE TITLE
Longer passwords in ykman

### ISSUE THREAD

**Issue by Nick2253** [Yubico/yubikey-manager#398]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: Brew
- Operating system and version: macOS Catalina
- YubiKey model and version: FIPS 4.4.5
- Bug description summary:

ykman does not support more than 38 character passwords or strong password policy flags (as found in YubiKey Personalization Tool)

Steps to reproduce
---

In YubiKey Personalization Tool, I'm able to set a static password with 64 modhex characters long, including the ability to set flags with "Upper and Lower case", "Alphanumeric", and "Send ! as prefix".  (See [this](https://support.yubico.com/hc/en-us/articles/360016614980-Understanding-Core-Static-Password-Features) article from Yubico for more information on this feature.)

Using either the Manager or the ykman tool, I see no way to reproduce this same feature on my Yubikey.  Trying to set a password using ykman presents a limit of 38 characters; this limit appears to be hard-coded into the code.

Other Thoughts
---

With my back-of-the-envelope math, a 64-character modhex password is about 3 orders of magnitude more secure than a 38 character ASCII password (assuming a random selection from all 94 printing ASCII characters).  Furthermore, many legacy password systems do not support many of the special characters that might be generated, significantly reducing the complexity (and therefore entropy) of the shorter password.

As part of our transition from single-factor password authentication to two-factor authentication, being able to support properly complicated pseudo-two-factor authentication is a huge step (for example, the first part of the password must be manually typed in (the know) and the second part (have) comes from the Yubikey).

**Comment by dainnilsson** [comment]
The YubiKey itself supports two different modes of "static password". One (static ticket mode) uses the Yubico OTP protocol, but with fixed counter values, resulting in an OTP that never changes. This produces a longer password (up to 64 character) but with less control over the output. 

The other (scan code mode), is by directly storing 38 keyboard scan codes, producing up to 38 character passwords. In this mode the user has more control over the resulting password and which characters are used.

One big difference is that in "static ticket mode" the password is not directly settable: You can't choose a specific password, you can only choose seed values from which it is generated. This also means that those seed values need to be backed up somewhere to be able to program the same password into a new YubiKey. This lowers the usability for this mode quite a bit: Users aren't able to set a specific password, and aren't able to transition to a new YubiKey while keeping the password, since those initial seed values often are lost.

For these reasons, we've chosen to only expose the "scan code mode" variant of static password in ykman. Even when restricting the character set to case-sensitive modhex (which gives the best compatibility when moving between computers using different keyboard layouts), a 38-character password gives you 190-bit security. We deem that to be well beyond the range of what is susceptible to brute force attack.

The other "static ticket mode" can still be programmed through the ykpersonalize command line tool.
