### ISSUE TITLE
ykman.cli.oath has duplicate options

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#427]
- YubiKey Manager (ykman) version: latest
- How was it installed?: 
- Operating system and version: Windows
- YubiKey model and version:
- Bug description summary: YubiKey Manager, OATH command line has two options that both use (-p)
- 
click.option(
    "-p",
    "--period",
    help="Number of seconds a TOTP code is valid.",

click_password_option = click.option(
    "-p", "--password", help="Provide a password to unlock the YubiKey."
)

Steps to reproduce
---

Run ykman oath accounts list -h
or
ykman oath accounts add -h

Expected result
---

password and period need to have unique dash-letter options

Actual results and logs
---

Not sure what actually gets ran if -p is used.

Other info
---

No

**Comment by aaronjsutton** [comment]
Without diving too far into it, looks like Click favors `--password` and not `--period` when using the `-p` flag. Temporarily removing the `password` option in the `add` command yields the expected:
```bash
$ poetry run ykman oath accounts add -p 120 "Phony" "LFXGYMC2LBGUWCQ="
$ poetry run ykman oath accounts list
120/Phony
...
```
As far as change, I think it would make sense to change `--period`, as `-p` and `--password` are more generic outside of the scope of OATH. A couple candidates:

- Use a capital `-P` for `--period` to differentiate. Some commands like [ssh](https://linux.die.net/man/1/ssh) seem to do this for unrelated options.
- Drop the short form `-p` of `--period` altogether

I couldn't find any example of capital short flags in other `ykman` options, so perhaps the second option would be more in line with the way the CLI is already structured.

Opened PR #430 for the second option since it was an easy fix, however probably going to want some input from the maintainers on the best way to rename the options.

**Comment by dainnilsson** [comment]
Thanks for spotting this! There are other short-form options which use capital letters in some of the other commands, so I would suggest we go with the first option and keep current behavior for `-p` being password, and introduce `-P` for period.

@aaronjsutton - do you mind updating your PR with that change?

**Comment by aaronjsutton** [comment]
Hm, guess I didn't look hard enough the first time - PR is updated. Thanks for your help!

**Comment by dainnilsson** [comment]
Thank you! The PR has been merged.
