### ISSUE TITLE
 yubikey-manager/doc/Library_Usage.adoc Need connection details for YubiKey v4 tokens

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#434]
- YubiKey Manager (ykman) version: latest
- How was it installed?: 
- Operating system and version: Windows
- YubiKey model and version: v4 Devices
- Bug description summary:

Document only shows connection for version >5.0.0, please provide details for v4 devices

Steps to reproduce
---

Running same code with version 4 devices yields:
  File "C:\Work\keygen\yubikit\oath.py", line 323, in put_credential
    self.protocol.send_apdu(0, INS_PUT, 0, 0, data)
  File "C:\Work\keygen\yubikit\core\smartcard.py", line 177, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6982

Expected result
---

[What did you expect to happen when you did the above?]

Actual results and logs
---

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by dainnilsson** [comment]
Since the error is happening within the `OathSession.put_credential` function, this indicates that you've already successfully connected to the YubiKey, as well as successfully established the session with the OATH application. The problem is occurring when trying to import a credential.

The error is an APDU error code: 0x6982. These are standardized codes, but not always very descriptive. I usually use this site as a reference: https://www.eftlab.com/knowledge-base/complete-list-of-apdu-responses/. Using that, we can look up this code in particular:

```
69	82	E	Security condition not satisfied.
```

This error is typical of attempting to send an instruction that is not allowed without first providing a PIN or password. For the OATH application this most likely means that the YubiKey is protected with a password. You will have to unlock the session before you can add/list/use/delete credentials:

```python
# Check if the session needs unlocking (if a password is set):
if oath_session.locked:
    # Ask the user for their password. This will show the password in the terminal, which is not what you want to use in production!
    password = input("Enter password to unlock:") 

    # Derive the unlock key from the password:
    key = oath_session.derive_key(password)

    # Then, use the derived key to unlock the session:
    oath_session.validate(key)

# Now you can add the credential:
oath_session.put_credential(...)
```

**Comment by wagner-robert** [comment]
I ran ykman oath reset and was able to provision the token again.  Thanks!
