### ISSUE TITLE
ykman otp setting - How to delete/remove an OTP access code? No prompt for old code

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#438]
- YubiKey Manager (ykman) version: latest
- How was it installed?: Git
- Operating system and version: WIndows
- YubiKey model and version: v5 FIPS
- Bug description summary:

When trying to remove an OTP access-code, ykman does not prompt for the old code like "ykman config set-lock-code -c" 

Steps to reproduce
---

C:\WINDOWS\system32>ykman otp settings -A f1b471fc7552 1
Update the settings for slot 1? All existing settings will be overwritten. [y/N]: y
Updating settings for slot 1...

C:\WINDOWS\system32>ykman otp settings --delete-access-code  1
Update the settings for slot 1? All existing settings will be overwritten. [y/N]: y
Updating settings for slot 1...
Error: Failed to write to the YubiKey. Make sure the device does not have restricted access.

The delete-access-code option does not appear to have an attribute HEX to enter the old code either.

Expected result
---

C:\WINDOWS\system32>ykman config set-lock-code -c
Enter your current lock code:

Actual results and logs
---

token is locked... cannot remove otp access code.

Other info
---
Are there really separate access codes for Slot 1 and Slot 2?

**Comment by RyanConMSFT** [comment]
A customer I'm working with is experiencing the same issue.  When attempting to use --delete-access-code for either slot the same error occurs.  I haven't tested if it occurs when only one slot is programmed.

**Comment by wagner-robert** [comment]
Confirmed this impacts:
Device type: YubiKey 5 NFC
Firmware version: 5.1.2

Device type: YubiKey FIPS
Firmware version: 4.4.5

Device type: YubiKey 5 NFC FIPS
Firmware version: 5.4.2

**Comment by wagner-robert** [comment]
YubiKey Manager (ykman) version: 4.0.3

**Comment by emlun** [comment]
The "current access code" option is on the `otp` command level, and shared between all the subcommands. So the correct invocation would be this:

```
$ ykman otp --access-code f1b471fc7552 settings --delete-access-code 1
Update the settings for slot 1? All existing settings will be overwritten. [y/N]: y
Updating settings for slot 1...
```

I agree the discoverability could be better, though. Maybe `--delete-access-code` could accept the current access code as an argument, or at least its help text should point out the dependency on `otp --access-code`.

**Comment by dainnilsson** [comment]
Yeah, this should be improved in the --help outputs for sure. To also answer the questions from @wagner-robert:

Both slots support having an (independent) access code, which protect each slot separately. Certain commands which modify both slots (such as the swap command) will not work if either slot has an access code set.

**Comment by dainnilsson** [comment]
ykman 4.0.7 has now been released which improves the `ykman otp --help` output, as well as some of the error messages.

**Comment by wagner-robert** [comment]
Any news on when this will get pushed out to the binary installations/download?  Windows x64.


Robert Wagner

________________________________

**Comment by dainnilsson** [comment]
The next release of YubiKey Manager GUI is unfortunately not planned until late October. In the meantime if you need a binary to test with, you could use the one included in the CI build from Github Actions: https://github.com/Yubico/yubikey-manager/actions/runs/1213012438

**Comment by ares487** [comment]
I'm not sure if this is your issue but if the problem is the "ERROR: Failed to write to the YubiKey. Make sure the device does not have restricted access (see "ykman otp --help" for more info)." code, and you are not 100% sure there is an access code on the slot from a previous user (e.g. if the key was bought new and was fresh out of tear-to-open packaging), then I think I have the solution.

I've just been getting railed for a couple hours by this issue and I fixed it by opening the windows version of yubico authenticator ver7.4.0 at https://www.yubico.com/products/yubico-authenticator/#h-download-yubico-authenticator as of 6th July 2026 (guessing any desktop version is fine just not mobile because I don't see the slots menu there), going to the slots menu on the left hand side, selecting the slot I wanted to configure, choosing the setup option (in my case challenge-response), generating a random key (to switch the slot configuration to that security protocol), then re-attempting configuration where I originally got violated and viola, it's alive! My intention was to make both slots challenge-response but the stock config of slot 1 is OTP so when I tried to select slot 1 to configure with challenge-response, I got the aforementioned error. Hope this helps
